version: '3.8'

services:
  postgres-lms:
    image: postgres:15-alpine
    container_name: postgres-lms
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loyalty_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-lms:
    image: redis:7-alpine
    container_name: redis-lms
    ports:
      - "6379:6379"

  rabbitmq-lms:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-lms
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
