server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/members/**, /v3/api-docs/member-service
          filters:
            - RewritePath=/v3/api-docs/member-service, /v3/api-docs
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/transactions/**, /v3/api-docs/transaction-service
          filters:
            - RewritePath=/v3/api-docs/transaction-service, /v3/api-docs
        - id: rule-management
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/rules/**, /v3/api-docs/rule-service
          filters:
            - RewritePath=/v3/api-docs/rule-service, /v3/api-docs
        - id: reward-service
          uri: http://localhost:8084
          predicates:
            - Path=/v3/api-docs/reward-service
          filters:
            - RewritePath=/v3/api-docs/reward-service, /v3/api-docs
        - id: event-api
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/events/**, /v3/api-docs/event-service
          filters:
            - RewritePath=/v3/api-docs/event-service, /v3/api-docs
        - id: product-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/products/**, /v3/api-docs/product-service
          filters:
            - RewritePath=/v3/api-docs/product-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Member Service
        url: /v3/api-docs/member-service
      - name: Transaction Service
        url: /v3/api-docs/transaction-service
      - name: Rule Service
        url: /v3/api-docs/rule-service
      - name: Reward Service
        url: /v3/api-docs/reward-service
      - name: Event Service
        url: /v3/api-docs/event-service
      - name: Product Service
        url: /v3/api-docs/product-service
